### ISSUE TITLE
New Software Sub Class

### ISSUE THREAD

**Issue by PPelchmann** [arago/MARS-Schema#45]
A new SoftwareSubClass for a Pentaho Reporting is needed.

**Comment by fotto** [comment]
do you refer to http://www.pentaho.com/product/product-overview?

is "Pentaho Reporting" really the correct product name?

**Comment by PPelchmann** [comment]
http://community.pentaho.com/projects/reporting/

**Comment by fotto** [comment]
suggesting
class=Reporting
subclas=PentahoReporting
