### ISSUE TITLE
New Software Class and associated sub classes required

### ISSUE THREAD

**Issue by Bryantp3** [arago/MARS-Schema#47]
Required:
A software class for Password Managers and/or storage vaults for secrets. 
One such softwaresubclass could be PMP for Password Manager Pro: 
https://www.manageengine.com/products/passwordmanagerpro/

**Comment by fotto** [comment]
What about 
class="IAM" (already exists)
subclass="PasswordManagerPro"

**Comment by Bryantp3** [comment]
Yes that would be good. 
Thanks.

**Comment by fotto** [comment]
will be added to version="5.3.5"
