### ISSUE TITLE
DBMS: SW Subclass for mongodb

### ISSUE THREAD

**Issue by jassmus** [arago/MARS-Schema#54]
One of my clients is working with mongo db and would like to use 
this as a SW Subclass under DBMS.

I would appreciate if you could update the schema accordingly and 
include that in the next release. 

Please let me know when it can be incorporated. 

Thanks in advance

Jan

https://de.wikipedia.org/wiki/MongoDB
https://www.mongodb.com/

**Comment by fotto** [comment]
will be added to schema version 5.3.5
