### ISSUE TITLE
New SW Sub Class

### ISSUE THREAD

**Issue by gibsonxavier** [arago/MARS-Schema#55]
Could you please add the below SW Sub class to the schema?

Class: MailServer

SubClass: Exchange/ ExchangeServer

**Comment by fotto** [comment]
are u requesting both sub-classes or may I choose one of them?

**Comment by gibsonxavier** [comment]
you may please choose one of them which is more appropriate. 
Thanks.

**Comment by fotto** [comment]
I'll take ExchangeServer
