### ISSUE TITLE
Support for Lotus Notes

### ISSUE THREAD

**Issue by lemorian** [arago/MARS-Schema#57]
Any plans on Adding IDM Domino platform to Software layer in the MARS Model?
Many Organizations still use it.

**Comment by fotto** [comment]
I would add
sw-class=Productivity
sw-sub-class=IBMDomino

any more suggestions?

**Comment by lemorian** [comment]
It is a 'groupware' but I think productivity is fine as well.

**Comment by fotto** [comment]
included
